In [2]:
import pandas as pd

In [3]:
df=pd.read_csv("titanic_train.csv")

In [4]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 118.9 KB

In [6]:
df[(df["Ticket"]=="W./C. 6607")]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
783,784,0,3,"Johnston, Mr. Andrew G",male,NaN,1,2,W./C. 6607,23.45,NaN,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S

In [7]:
df["Embarked"].value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [8]:
df[(df["Embarked"].isnull())]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
61,62,1,1,"Icard, Miss. Amelie",female,38.0,0,0,113572,80.0,B28,NaN
829,830,1,1,"Stone, Mrs. George Nelson (Martha Evelyn)",female,62.0,0,0,113572,80.0,B28,NaN

In [9]:
df["Embarked"]=df["Embarked"].fillna("S")

In [10]:
df[df["Ticket"]=="113572"]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
61,62,1,1,"Icard, Miss. Amelie",female,38.0,0,0,113572,80.0,B28,S
829,830,1,1,"Stone, Mrs. George Nelson (Martha Evelyn)",female,62.0,0,0,113572,80.0,B28,S

In [11]:
df["Age"].mean()

np.float64(29.69911764705882)

In [12]:
df["Age"].median()

np.float64(28.0)

In [13]:
df["Age"].max()

np.float64(80.0)

In [14]:
df["Age"].min()

np.float64(0.42)

In [15]:
df1 = df[df["Pclass"]==1]
df1["Age"].mean()

np.float64(38.233440860215055)

In [16]:
df2=df1[df1["Sex"]=="male"]
df2["Age"].mean()

np.float64(41.28138613861386)

In [17]:
print("Class 1 Male",df[(df["Pclass"]==1)&(df["Sex"]=="male")]["Age"].mean())
print("Class 1 Female",df[(df["Pclass"]==1)&(df["Sex"]=="female")]["Age"].mean())
print("Class 2 Male",df[(df["Pclass"]==2)&(df["Sex"]=="male")]["Age"].mean())
print("Class 2 Female",df[(df["Pclass"]==2)&(df["Sex"]=="female")]["Age"].mean())
print("Class 3 Male",df[(df["Pclass"]==3)&(df["Sex"]=="male")]["Age"].mean())
print("Class 3 Female",df[(df["Pclass"]==3)&(df["Sex"]=="female")]["Age"].mean())

Class 1 Male 41.28138613861386
Class 1 Female 34.61176470588235
Class 2 Male 30.74070707070707
Class 2 Female 28.722972972972972
Class 3 Male 26.507588932806325
Class 3 Female 21.75

In [18]:
df[(df["Age"].isnull()) & (df["Pclass"]==1) & (df["Sex"]=="male")]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
55,56,1,1,"Woolner, Mr. Hugh",male,NaN,0,0,19947,35.5000,C52,S
64,65,0,1,"Stewart, Mr. Albert A",male,NaN,0,0,PC 17605,27.7208,NaN,C
168,169,0,1,"Baumann, Mr. John D",male,NaN,0,0,PC 17318,25.9250,NaN,S
185,186,0,1,"Rood, Mr. Hugh Roscoe",male,NaN,0,0,113767,50.0000,A32,S
270,271,0,1,"Cairns, Mr. Alexander",male,NaN,0,0,113798,31.0000,NaN,S
284,285,0,1,"Smith, Mr. Richard William",male,NaN,0,0,113056,26.0000,A19,S
295,296,0,1,"Lewy, Mr. Ervin G",male,NaN,0,0,PC 17612,27.7208,NaN,C
298,299,1,1,"Saalfeld, Mr. Adolphe",male,NaN,0,0,19988,30.5000,C106,S
351,352,0,1,"Williams-Lambert, Mr. Fletcher Fellows",male,NaN,0,0,113510,35.0000,C128,S
475,476,0,1,"Clifford, Mr. George Quincy",male,NaN,0,0,110465,52.0000,A14,S
507,508,1,1,"Bradley, Mr. George (""George Arthur Brayton"")",male,NaN,0,0,111427,26.5500,NaN,S
527,528,0,1,"Farthing, Mr. John",male,NaN,0,0,PC 17483,221.7792,C95,S
557,558,0,1,"Robbins, Mr. Victor",male,NaN,0,0,PC 17757,227.5250,NaN,C
602,603,0,1,"Harrington, Mr. Charles H",male,NaN,0,0,113796,42.4000,NaN,S
633,634,0,1,"Parr, Mr. William Henry Marsh",male,NaN,0,0,112052,0.0000,NaN,S
711,712,0,1,"Klaber, Mr. Herman",male,NaN,0,0,113028,26.5500,C124,S
740,741,1,1,"Hawksford, Mr. Walter James",male,NaN,0,0,16988,30.0000,D45,S
766,767,0,1,"Brewe, Dr. Arthur Jackson",male,NaN,0,0,112379,39.6000,NaN,C
793,794,0,1,"Hoyt, Mr. William Fisher",male,NaN,0,0,PC 17600,30.6958,NaN,C
815,816,0,1,"Fry, Mr. Richard",male,NaN,0,0,112058,0.0000,B102,S
839,840,1,1,"Marechal, Mr. Pierre",male,NaN,0,0,11774,29.7000,C47,C

In [19]:
df["Age1"]=df["Age"]

In [20]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age1
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,22.0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,38.0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,26.0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,35.0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,35.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,27.0
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,19.0
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,NaN
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,26.0
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,32.0

In [21]:
df.loc[(df["Age1"].isnull()) & (df["Pclass"]==1) & (df["Sex"]=="male"),"Age1"]= df[(df["Pclass"]==1)&(df["Sex"]=="male")]["Age"].mean()
df.loc[(df["Age1"].isnull()) & (df["Pclass"]==1) & (df["Sex"]=="female"),"Age1"]= df[(df["Pclass"]==1)&(df["Sex"]=="female")]["Age"].mean()
df.loc[(df["Age1"].isnull()) & (df["Pclass"]==2) & (df["Sex"]=="male"),"Age1"]= df[(df["Pclass"]==2)&(df["Sex"]=="male")]["Age"].mean()
df.loc[(df["Age1"].isnull()) & (df["Pclass"]==2) & (df["Sex"]=="female"),"Age1"]= df[(df["Pclass"]==2)&(df["Sex"]=="female")]["Age"].mean()
df.loc[(df["Age1"].isnull()) & (df["Pclass"]==3) & (df["Sex"]=="male"),"Age1"]= df[(df["Pclass"]==3)&(df["Sex"]=="male")]["Age"].mean()
df.loc[(df["Age1"].isnull()) & (df["Pclass"]==3) & (df["Sex"]=="female"),"Age1"]= df[(df["Pclass"]==3)&(df["Sex"]=="female")]["Age"].mean()

In [22]:
df[(df["Age1"].isnull())]

Empty DataFrame
Columns: [PassengerId, Survived, Pclass, Name, Sex, Age, SibSp, Parch, Ticket, Fare, Cabin, Embarked, Age1]
Index: []

In [23]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     891 non-null    str
 12  Age1         891 non-null    float64
dtypes: float64(3), int64(5), str(5)
memory usage: 125.7 KB

In [24]:
df["Embarked"].value_counts()

Embarked
S    646
C    168
Q     77
Name: count, dtype: int64

In [25]:

mapping = {"S": 0, "C": 1, "Q": 2}


df["Embarked"] = df["Embarked"].map(mapping).astype("Int64")

In [26]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     891 non-null    Int64
 12  Age1         891 non-null    float64
dtypes: Int64(1), float64(3), int64(5), str(4)
memory usage: 125.7 KB

In [27]:
mapping = {"male": 0, "female": 1}


df["Sex"] = df["Sex"].map(mapping).astype("Int64")

In [28]:
df["Sex"].value_counts()

Sex
0    577
1    314
Name: count, dtype: Int64

In [29]:
df["Age1"].median()

np.float64(26.507588932806325)

In [30]:
df.loc[(df["Age1"]<21.75) ,"age count"]=0
df.loc[(df["Age1"]>=21.75) & (df["Age1"]<26.5),"age count"]=1
df.loc[(df["Age1"]>=26.5) & (df["Age1"]<36),"age count"]=2
df.loc[(df["Age1"]>=36) ,"age count"]=3

In [31]:
df["age count"].value_counts()

age count
2.0    292
3.0    238
0.0    204
1.0    157
Name: count, dtype: int64

In [32]:
df["age count"]=df["age count"].astype("Int64")

In [33]:
from sklearn.linear_model import LogisticRegression

In [34]:
df1=df.drop(['PassengerId','Name','Age' ,'SibSp',"Parch","Ticket","Fare","Cabin","Age1"],axis=1)

In [35]:
df1

     Survived  Pclass  Sex  Embarked  age count
0           0       3    0         0          1
1           1       1    1         1          3
2           1       3    1         0          1
3           1       1    1         0          2
4           0       3    0         0          2
..        ...     ...  ...       ...        ...
886         0       2    0         0          2
887         1       1    1         0          0
888         0       3    1         0          1
889         1       1    0         1          1
890         0       3    0         2          2

[891 rows x 5 columns]

In [36]:
X=df1.drop("Survived",axis=1)

In [37]:
y=df1["Survived"]

In [38]:
from sklearn.model_selection import train_test_split

In [39]:
X_train, X_test, y_train, y_test=train_test_split(X,y, test_size=0.2, random_state=101)

In [40]:
X_test

     Pclass  Sex  Embarked  age count
331       1    0         0          3
700       1    1         1          0
748       1    0         0          0
751       3    0         0          0
481       2    0         0          2
..      ...  ...       ...        ...
154       3    0         0          2
454       3    0         0          2
879       1    1         1          3
771       3    0         0          3
466       2    0         0          2

[179 rows x 4 columns]

In [41]:
from sklearn.linear_model import LogisticRegression

In [42]:
lr=LogisticRegression()

In [43]:
lr.fit(X_train, y_train)

LogisticRegression()

In [44]:
y_pred=lr.predict(X_test)

In [45]:
y_pred

array([0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 0])

In [46]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [47]:
accuracy_score(y_test, y_pred)

0.8044692737430168

In [48]:
Pclass=1
Sex=0
Embarked=0
age_count=0

In [49]:
lr.predict([[Pclass,Sex,Embarked,age_count]])[0]

/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

np.int64(1)